-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 00:11:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `integrador` DEFAULT CHARACTER SET utf8 ;
USE `integrador` ;

-- -----------------------------------------------------
-- Table `integrador`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`user` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `nacimiento` DATE NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `integrador`.`server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`server` (
  `id_servidor` INT NOT NULL AUTO_INCREMENT,
  `nombre_servidor` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_servidor`),
  UNIQUE INDEX `nombre_servidor_UNIQUE` (`nombre_servidor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integrador`.`user_server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`user_server` (
  `id_usuario_servidor` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_servidor` INT NOT NULL,
  PRIMARY KEY (`id_usuario_servidor`),
  INDEX `fk_user_has_server_server1_idx` (`id_servidor` ASC) VISIBLE,
  INDEX `fk_user_has_server_user_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_server_user`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `integrador`.`user` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_server_server1`
    FOREIGN KEY (`id_servidor`)
    REFERENCES `integrador`.`server` (`id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `integrador`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`channel` (
  `id_canal` INT NOT NULL AUTO_INCREMENT,
  `nombre_canal` VARCHAR(45) NOT NULL,
  `id_servidor` INT NOT NULL,
  PRIMARY KEY (`id_canal`),
  INDEX `fk_channel_server1_idx` (`id_servidor` ASC) VISIBLE,
  UNIQUE INDEX `nombre_canal_UNIQUE` (`nombre_canal` ASC) VISIBLE,
  CONSTRAINT `fk_channel_server1`
    FOREIGN KEY (`id_servidor`)
    REFERENCES `integrador`.`server` (`id_servidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integrador`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`chats` (
  `id_chats` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(250) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `id_canal` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_chats`),
  INDEX `fk_chats_channel1_idx` (`id_canal` ASC) VISIBLE,
  INDEX `fk_chats_user1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_chats_channel1`
    FOREIGN KEY (`id_canal`)
    REFERENCES `integrador`.`channel` (`id_canal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_user1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `integrador`.`user` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `integrador`.`user_channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `integrador`.`user_channel` (
  `id_usuario_canal` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_canal` INT NOT NULL,
  PRIMARY KEY (`id_usuario_canal`),
  INDEX `fk_user_has_channel_channel1_idx` (`id_canal` ASC) VISIBLE,
  INDEX `fk_user_has_channel_user1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_channel_user1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `integrador`.`user` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_channel_channel1`
    FOREIGN KEY (`id_canal`)
    REFERENCES `integrador`.`channel` (`id_canal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
